name: usage_log_flutter
description: "An Usage Log for Android built with Flutter."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  android_package_manager: ^0.7.0
  mobile_device_identifier: ^0.0.3

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.13
  intl: ^0.20.1
  usage_stats: ^1.2.0
  device_info: ^2.0.3
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default-icon.png
    - assets/lock-icon.png
